import requests
import json
import pandas as pd
import time
import csv

# Replace with your actual API token
api_token = "Insert Salling Group API key here"

# API endpoint
url_template = "https://api.sallinggroup.com/v1/food-waste/?geo={lat},{lon}&radius={radius}"

# Headers with authorization token
headers = {
    "Authorization": f"Bearer {api_token}"
}

def salling_api(coordinates, radius):

    # List to store the results
    rows = []
    products = []

    url = url_template.format(lat=coordinates[0], lon=coordinates[1], radius=radius)
    response = requests.get(url, headers=headers)

    if response.status_code == 200:
        data = response.json()
        for store_data in data:
            store = store_data["store"]
            store_name = f'"{store["name"]}"'
            store_brand = store["brand"]
            store_city = store["address"]["city"]
            store_street = store["address"]["street"]
            store_zip = store["address"]["zip"]
            store_lat, store_lon = store["coordinates"]
            
            for clearance in store_data["clearances"]:
                offer = clearance["offer"]
                product = clearance["product"]
                products.append(product["description"])
                
                # Get categories and extract only the first one
                categories = product.get('categories', {}).get('en', 'Unknown')
                first_category = categories.split(">")[0] if categories else "Unknown"
                
                # Store data row
                rows.append({
                    "Store Name": store_name,
                    "Brand": store_brand,
                    "City": store_city,
                    "Street": store_street,
                    "Zip Code": store_zip,
                    "Latitude": store_lat,
                    "Longitude": store_lon,
                    "Product Description": product["description"],
                    "Category": first_category,  # Only first category
                    "Product EAN": product["ean"],
                    "Product Image": product["image"],
                    "Original Price (DKK)": offer["originalPrice"],
                    "New Price (DKK)": offer["newPrice"],
                    "Discount (DKK)": offer["discount"],
                    "Discount (%)": offer["percentDiscount"],
                    "Stock": offer["stock"],
                    "Stock Unit": offer["stockUnit"],
                    "Offer Start Time": offer["startTime"],
                    "Offer End Time": offer["endTime"],
                    "Last Update": offer["lastUpdate"]
                })
    else:
        print(f"Failed to retrieve data")

    # Convert list to DataFrame
    df = pd.DataFrame(rows)

    # Save to CSV file
    #df.to_csv("store_clearance_data.csv", index=False, encoding="utf-8-sig", quoting=csv.QUOTE_ALL)  # Force quotes around all fields

    return products, df

def estimated_emissions(product_name):

    estimated_emissions = [
        ("HØRFRØ RUGBRØD GAMLE MØLLE", 0.14),
        ("SKINKESTRIMLER NÆMT", 3.63),
        ("RØGET FILET EGELYKKE", 0.84),
        ("HERKULES KOHBERG", 1.48),
        ("FRANSK LEVERPOSTEJ STRYHNS", 2.06),
        ("GROVHAK. LEVERPOSTEJ STRYHNS", 3.35),
        ("KYL.BRYST M/URTER MINIMUM", 1.87),
        ("SPEGEPØLSE ØGO", 1.92),
        ("RAV 15 MD 180G CMT", 0.54),
        ("SKOVMAND SCHULSTAD", 1.64),
        ("PERLE CMT", 1.96),
        ("STEGT KYLLINGEBRYST MINIMUM", 2.35),
        ("ROASTBEEF SMAGEN AF AARHUS", 4.09),
        ("PÅSKEPANDEKAGE BRUGSE", 0.89),
        ("BURGERBØF ØGO", 1.35),
        ("FLÆSK I SKIVER VELSMAG", 3.98),
        ("GROVHAK. LEVERPOSTEJ EGELYKKE", 4.14),
        ("LEVAIN SURDEJ PÅGEN", 1.92),
        ("BURGERBOOST SMOKEY DANISH CROWN", 4.66),
        ("PEPPERONI PIZZA CASA T", 1.05),
        ("RIS M/KYLLING/LEMON NÆMT", 2.33),
        ("MARQUIS CASTELLO", 1.27),
        ("DANABLU SKIVER CASTELLO", 1.23),
        ("BACON LEVERPOSTEJ BORNHOLMERSLAGTEREN", 2.58),
        ("BURRATA ZANETTI", 1.33),
        ("GUACAMOLE SALLING", 0.62),
        ("FALAFEL SUPER KRÆS", 1.54),
        ("SKINKESALAT FIN K-SALAT", 4.58),
        ("KOLDSKÅL M/CIT. KLØVER", 1.77),
        ("CHIA BOLLER LEVEBRØD", 0.22),
        ("FLADBRØD LIBA", 0.16),
        ("FULDKORNSBOL. LEVEBRØD", 0.07),
        ("BAGERENS RUGBRØ KOHBERG", 1.99),
        ("BUTTERDEJ SALLING", 1.38),
        ("MAXI KING 3-PAK KINDER", 1.41),
        ("VEGANSK HOT DOG POH", 1.56),
        ("KYLLINGEDELLER SALLING", 1.09),
        ("C. FRAICHE 13% ARLA LF", 1.09),
        ("SANDW TUN/CHILI BY KAVSMAN", 1.56),
        ("FOOD TO GO VANI ARLA PROTEIN", 1.64),
        ("FOOD TO GO CHOC ARLA PROTEIN", 1.05),
        ("PROTEINPANDEK. MAMMA", 0.63),
        ("FRIKADELLEPØLSE 3-STJERNET", 1.24),
        ("WASA FALU FALU", 1.57),
        ("OSTEHAPS LILLEBROR", 3.41),
        ("SCHWARZBROT GAMLE MØLLE", 1.41),
        ("KOTELETTER ØGO", 1.49),
        ("LAMMECULOTTE PREMIEUR", 12.44),
        ("CROISSANT SKINKE/OST NÆMT", 3.12),
        ("LANGTIDSKOGT SKINKE AALBÆK", 3.64),
        ("RULLEPØLSE ØGO", 2.65),
        ("KYLLINGEBRYST EGELYKKE", 2.04),
        ("RØGET MEDISTER 3-STJERNET", 1.89),
        ("SMAGFULD BOLLER KOHBERG", 0.19),
        ("MULTIKERNE SANDWICH SCHULSTAD", 1.17),
        ("FULDKORNSTOAST GAMLE MØLLE", 1.01),
        ("KERNERUGBRØD GAMLE MØLLE", 0.2),
        ("SOLSKINSBOLLER KOHBERG", 0.21),
        ("ØKO NATUREL ARLA CULTURA", 0.59),
        ("KEFIR VANILJE ARLA CULTURA", 0.49),
        ("LF KOLDSKÅL 1% CHEASY", 1.14),
        ("LETMÆLK EGELYKKE", 0.38),
        ("BEARNAISESAUCE S. COOKING", 1.19),
        ("BACON 3-PAK TULIP", 1.57),
        ("HYTTEOST FRUGT PROTEIN LAB", 2.85),
        ("KERNERUGBRØD ØGO", 0.17),
        ("BACON-PEBER POSTEJ STRYHNS", 3.58),
        ("GYROS AF GRIS DET HURTIGE KØKKEN", 1.45),
        ("GULERODSBOLLER GAMLE MØLLE", 0.23),
        ("KYLLINGESAUCE JENSENS", 1.64),
        ("KOLDSKÅL KLØVER", 0.97),
        ("TRØFFEL PHILADELPHIA", 0.74),
        ("TUNSALAT GRAASTEN", 0.51),
        ("PESTO PEBERFRUGT LØGISMOSE", 0.64),
        ("KALKUNBRYST EGELYKKE", 1.72),
        ("FLØDEKARTOFLER BACON PEKA", 0.98),
        ("UMAMI SØHØJLAND", 1.22),
        ("MADLAVNINGSFLØDE 8% ARLA", 1.41),
        ("SPAGHETTI BOLOG NÆMT", 2.07),
        ("CROISSANTDEJ DANEROLLES", 1.39),
        ("KARRY SALAT GRAASTEN", 0.67),
        ("ØKO CREME F 18% LØGISMOSE", 0.91),
        ("XXL SERRANO SERRANO", 3.46),
        ("HÖNÖ BOHUSKAKA PÅGEN", 1.2),
        ("PEPPERONI CALA. SMARTCOOKING", 2.78),
        ("VEGGIE KEBAB SUPER KRÆS", 1.1),
        ("SURDEJSBOLLER ØGO", 0.15),
        ("CHILI SALAMI AALBÆK", 4.04),
        ("A38 NATUREL ARLA CULTURA", 1.52),
        ("YOGHURT PEACH MELBA EGELYKKE", 0.6),
        ("YOGHURT JORDBÆR EGELYKKE", 0.79),
        ("ØKO YOGHURT NATUREL LØGISMOSE", 0.69),
        ("GREVEFEDT LAMPE", 13.39),
        ("BRIE PRÉSIDENT", 2.93),
        ("FRANSK LEVERPOSTEJ BORNHOLMERSLAGTEREN", 3.56),
        ("ØKO SKUMMETMÆLK LØGISMOSE", 0.51),
        ("TÆRTEDEJ NÆMT", 1.46),
        ("GUDHJEM SPEGE BORNHOLMER", 1.82),
        ("RØGET MØRBRAD PREMIEUR", 1.85),
        ("PISKEFLØDE 36% ARLA", 0.51),
        ("CHEESE/BBQ LAMPE", 8.39),
        ("FRAICHE 5% CHEASY", 0.79),
        ("MOZZARELLA KAROLINES", 1.85),
        ("HVEDESANDWICH GAMLE MØLLE", 0.99),
        ("FRANSK BRIE MON AMI", 4.68),
        ("XMATURE CHEDDAR CASTELLO", 2.17),
        ("MINI CHEDDAR BABYBEL", 2.48),
        ("FLÆSKESTEG VELSMAG", 1.62),
        ("FULDKORNSBOLLER SCHULSTAD", 0.22),
        ("SANDWICH RUGBRØ LEVEBRØD", 0.19),
        ("KRYDDERBOLLER FK GAMLE MØLLE", 0.08),
        ("SKIVEOST GRØNNELUND", 2.71),
        ("HØNSESALAT GRAASTEN", 0.7),
        ("BACH SCHINKE SMAGEN AF AARHUS", 0.82),
        ("THEM ML SKIVER 175 G - ØKO", 0.63),
        ("PANDEKAGER NÆMT", 0.79),
        ("GROVHAK. LEVERPOSTEJ BORNHOLMERSLAGTEREN", 5.1),
        ("PEBERSALAMI GØL", 4.09),
        ("HVIDLØGSSALAM GØL", 13.95),
        ("ÅLERØGET SALAMI GØL", 10.79),
        ("BUTERDEJSSTÆNGE LA FABRIQUE", 1.55),
        ("PULLED PORK TULIP", 1.55),
        ("MINI LIGHT BABYBEL", 1.12),
        ("JÆGERPØLSE 3-STJERNET", 1.56),
        ("HAVARTI 55+ MAMMEN", 1.01),
        ("OSTEDIP M STICK DIPPERS", 2.07),
        ("OSTEDIP M. KIKS DIPPERS", 1.79),
        ("TOPAS 28% CHEESEMAKERS", 0.96),
        ("BLINIS PREMIEUR", 0.69),
        ("KARTOFFEL SANDWICH KOHBERG", 0.52),
        ("TZATZIKI ATHENA", 1.81),
        ("KYL.DELLER DDGF", 2.39),
        ("KYL.DEL HVIDLØG DDGF", 2.24),
        ("GULD 45+ ML MAMMEN", 0.67),
        ("STADION FRANK LAMPE", 9.99),
        ("KARTOFFELSALAT FLENSTED", 0.61),
        ("KNÆKBRØD M/SESA FINN CRISP", 0.09),
        ("SAINT MORGAN PRESIDENT", 1.41),
        ("CHEESECAKE TOBLERONE", 1.58),
        ("HAMBURGERRYG EGELYKKE", 1.89),
        ("OKSEBRYST SMAGEN AF AARHUS", 10.27),
        ("OKSESPEGEPØLSE ØGO", 4.76),
        ("KYLLING-BACON SALAT K-SALAT", 1.6),
        ("KARTOFFELSALAT PERS. GRAASTEN SJ.FRISTEL.", 0.48),
        ("KARTOFFELSALAT M/DIL FLENSTED", 0.69),
        ("GRILLPØLSER PØLSEMESTEREN", 3.14),
        ("BUTTERDEJ NÆMT", 0.93),
        ("SAMSØ ML 30+ EGELYKKE", 1.73),
        ("FRANKFURTER PØLSEMESTEREN", 4.6),
        ("HONNINGSKINKE MINIMUM", 2.63),
        ("KØDPØLSE 3-STJERNET", 2.79),
        ("BRILLIANT 30% CHEESEMAKERS", 1.73),
        ("RUGBRØDSBOLLER KOHBERG", 0.18),
        ("RULLEPØLSE PÅLÆKKER", 2.78),
        ("BURGUNDERSKINKE MINIMUM", 3.28),
        ("KYLLINGEBRYST MINIMUM", 1.22),
        ("SOLSIKKESTYKKER GAMLE MØLLE", 1.33),
        ("DET GODE SOL BOLLER SCHULSTAD", 0.12),
        ("SAN. KYL. TOMAT PÅLÆKKER", 1.19),
        ("MAR. NAKKEKOT. VELSMAG", 1.86),
        ("BBQ/HVIDL. KOT. VELSMAG", 0.75),
        ("HAMBURGERRYG PÅLÆKKER", 1.53),
        ("PISKEFLØDE 36% EGELYKKE", 0.54),
        ("PØLSEHORNSDEJ NÆMT", 1.61),
        ("ITALIENSK SALAT GRAASTEN", 0.26),
        ("KRYDDERBOLLER GAMLE MØLLE", 0.11),
        ("SALSICCIA TRØFF PREMIEUR", 1.13),
        ("XXL CHORIZO XXL", 1.26),
        ("FAVORIT SAUCE S. COOKING", 1.7),
        ("RIBS HVIDLØG NÆMT", 1.5),
        ("PURLØG PHILADELPHIA", 1.54),
        ("BLÅSKIMMEL OST SAINT AGUR", 3.21),
        ("CHEEZ AND FUN LEENDE KO", 1.89),
        ("TULIP BACONTERN TULIP", 1.83),
        ("BACON POSTEJ STRYHNS", 1.55),
        ("BRIE INTENSE PRÉSIDENT", 4.83),
        ("L'OVALE BRIE PRESIDENT", 2.79),
        ("RIBS TERIYAKI NÆMT", 1.13),
        ("BACON 5-PAK TULIP", 0.86),
        ("SMARAGD CMT", 1.97),
        ("FLYDENDE AMA", 1.2),
        ("FRUGT+TE FERSK GOD MORGEN", 0.42),
        ("YOGHURTBOLLER KOHBERG", 0.47),
        ("ØKO SØDMÆLK ARLA ØKO", 0.45),
        ("SOLSIKKERUGBR. DET GODE", 1.36),
        ("MULTIKER BOLLER LEVEBRØD", 0.15),
        ("JAVISST PÅGEN", 1.08),
        ("GROV CAFE SANDW KOHBERG", 0.6),
        ("GILLELEJE HAVN SIGNATURBRØD", 0.1),
        ("SOLSIKKERUGBRØD SALLING", 0.1),
        ("GB URTEKYLLING", 1.35),
        ("MØRBRAD M KAR. GODT BEGYNDT", 1.47),
        ("MØRBRAD M/KAR. GODT BEGYNDT", 1.41),
        ("MØRBRAD M. GRATIN GODT BEGYNDT", 1.0),
        ("DANONINO 6X50 G.", 0.66),
        ("MINI FUET SALLING", 0.9),
        ("MINI CHORIZO SALLING", 0.67),
        ("HVIDLØGSPATE STEFF H.", 1.39),
        ("WRAP KYL/KARRY SALLING NU", 2.07),
        ("LAMMEMØRBRAD LUDVIG", 14.04),
        ("RØGET MØRBRAD PRINCIP", 1.01),
        ("PORT SALUT", 1.52),
        ("PISKEFLØDE 36% KAROLINE'S", 1.3),
        ("KYL.BRYST KRYD SALLING", 1.48),
        ("KROSALAMI DELIKA", 12.59),
        ("HAMBURGERBOLLER SALLING", 0.18),
        ("KALKUNBRYST BUDGET", 1.24),
        ("45+ ML M/KOMMEN MAMMEN", 0.88),
        ("VANILJE POUCH DANONINO", 1.46),
        ("ØKO MINIMÆLK NATURMÆLK", 0.71),
        ("INGEFÆR SHOT INNOCENT", 0.68),
        ("LIME/CITRON ALPRO", 1.49),
        ("VIKING I SKIVER KOHBERG", 0.63),
        ("BLÅSKIMMEL RONDELÉ", 1.0),
        ("SERRANO WRAP SALLING", 1.49),
        ("RULLEPØLSE SALLING", 4.46),
        ("HUMMUS M. TOMAT SALLING", 1.03),
        ("LAMMEFILET U/FE LUDVIG", 8.68),
        ("HONNING 0% FEDT ATHENA", 1.41),
        ("PEPPADEW M OST SALLING", 3.37),
        ("SNITTE MUNCHMALLOW", 1.38),
        ("FRANKFURTER SLAGTEREN", 1.47),
        ("SKINKE FRILANDS", 2.35),
        ("APPELSINJUICE SALLING", 0.17),
        ("JORDBÆR/BANAN DANONINO DUO", 1.32),
        ("STG BACON SKIVE TULIP", 1.85),
        ("COPPA MED OST SALLING", 4.0),
        ("BØFFELMOZZAREL. PRINCIP", 1.75),
        ("KYLL. TERN SALLING", 1.65),
        ("RUSSISK SALAT K-SALAT", 0.56),
        ("SKAGENSALAT GRAASTEN SMJ", 0.41),
        ("MINIFRIKADELLER SALLING", 1.86),
        ("APPELSINNEKTAR SALLING", 1.09),
        ("SANDWICHSKINKE SALLING", 4.21),
        ("RØGET RULLEPØLS SALLING", 1.39),
        ("KALKUNBRYST PÅLÆKKER", 0.57),
        ("KALKUNBRYST SALLING", 1.19),
        ("RISOTTO CHAMPIG SALLING NU", 1.4),
        ("BURRATA PESTO ZANETTI", 1.64),
        ("KYLLING BACON K-SALAT", 0.76),
        ("SVAMPE BURGER WAUW!", 0.55),
        ("KAMSTEG PÅLÆKKER", 1.23),
        ("GULERODSBRØD DET GODE", 0.18),
        ("HAVREBR. KERNER SALLING", 0.78),
        ("BONDEBRØD SALLING", 0.11),
        ("GROV SANDWICH SCHULSTAD", 1.57),
        ("KEBABBRØD SUPER KRÆS", 0.15),
        ("HAMBURGERRYG PRINCIP", 1.66),
        ("PÅSKE SALAMIHAP PÅLÆKKER", 7.8),
        ("RULLEPØLSE AALBÆK", 4.6),
        ("MØRKT RUGBRØD SALLING", 0.22),
        ("ROASTBEEF 3 STJERNET", 9.35),
        ("LAMMECULOTTE LUDVIG", 12.03),
        ("HAMBURGERRYG BUDGET", 1.72),
        ("CITRONKYLLING WOODEN SPOON", 1.02),
        ("KYLLINGEGRYDE MK", 2.25),
        ("KYLLING SUR/SØD SALLING NU", 0.78),
        ("KOLDSKÅL M. TOP ARLA", 0.64),
        ("SPAGHETTI PASTELLA", 1.03),
        ("YOGHURT ORANGE SALLING ØKO", 0.55),
        ("SKINKETERN SALLING", 4.68),
        ("SKINKESTRIMLER STEFF H.", 3.8),
        ("RAMSLØGSGRILLER CARL V.", 1.21),
        ("GRILLFAKLER SLAGTEREN", 1.73),
        ("HOTDOGPØLSER STEFF H.", 1.52),
        ("BAYERSKE PØLSER STEFF H.", 4.53),
        ("SOMMERGRILLER CARL V.", 1.4),
        ("KYLLINGEPØLSE SALLING", 1.14),
        ("INNER WINNER INNOCENT", 1.4),
        ("PUDDING VANILJE ALPRO", 1.31),
        ("SKAGENSBRØD SCHULSTAD", 0.09),
        ("WIENERPØLSER GØL", 1.82),
        ("HOTDOGPØLSER GØL", 4.28),
        ("MADPANDEKAGER SALLING", 0.57),
        ("GRAVAD FILET PRINCIP", 2.0),
        ("SKINKE PRINCIP", 3.02),
        ("BLINIS SALLING", 1.81),
        ("RISOTTO TRØFFEL SALLING NU", 1.75),
        ("GULEROD BITE HANI'S", 0.75),
        ("Æ'BACON NATURLI", 0.9),
        ("LA SELECTION HAUTE FROMAG", 1.8),
        ("SANDWICH SALAMI SALLING NU", 4.84),
        ("LIGHT MINI BABYBEL", 0.74),
        ("GRI OLIVEN MARI SALLING", 1.38),
        ("RISENGRØD SALLING NU", 0.94),
        ("SANDW. KYLLING BY KAVSMAN", 1.21),
        ("KARRY KYL/BACON READY-TO-EAT", 1.87),
        ("GRÆSK Y. 0% JOR ATHENA", 1.22),
        ("KEFIR JORDBÆR ACTIVIA", 0.72),
        ("G. YOGH. BLÅBÆR ATHENA", 2.0),
        ("HUMMUS SPICY SALLING", 0.81),
        ("SANDW. TOM/MOZ BY KAVSMAN", 0.74),
        ("WRAP BBQ/KYL BY KAVSMANN", 1.87),
        ("SKINKESTRIMLER BUDGET", 2.7),
        ("TIRAMISU SOLO ITALIA", 0.76),
        ("RÖSTI STICKS CREATIVE P.", 1.22),
        ("WRAP KYL/TERIYA BY KAVSMANN", 1.4),
        ("HUMMUS TOMAT SALLING ØKO", 1.0),
        ("HUMMUS RØDBEDE SALLING", 0.7),
        ("SANDW. ÆG/BACON SALLING NU", 1.78),
        ("CHIAGRØD MANGO TPK", 0.76),
        ("RG. RULLEPØLSE PRINCIP", 2.62),
        ("HINDBÆR DRIK ARLA PROTEIN", 1.59),
        ("BLOMKÅL BITE HANI'S", 1.51),
        ("OKSESPEGEPØLSE FRILANDS", 4.77),
        ("KYLLINGEBRYST SALLING", 1.01),
        ("HONNING SKINKE SALLING", 1.68),
        ("ÆBLE/DRUE/PÆRE INNOCENT", 0.93),
        ("OKSEBRYST SALLING", 5.48),
        ("LAMMESKANKER LUDVIG", 6.55),
        ("KEBAB'ISH SANDW NATURLI'", 1.36),
        ("ITALIENSK TPK", 1.11),
        ("HINDBÆR DRIKYOG ACTIVIA", 1.21),
        ("SOMMERSALAT K-SALAT", 0.31),
        ("RULLEPØLSE FRILANDS", 2.66),
        ("HAMBURGERRYG FRILANDS", 1.57),
        ("OKSEBRYST PRINCIP", 5.07),
        ("RULLEPØLSE PRINCIP", 4.05),
        ("HØNSESALAT SALLING", 0.32),
        ("HAMBURGERRYG SALLING", 1.65),
        ("ITALIENSK SALAT SALLING", 0.44),
        ("GRILLPØLSER LAMPE", 10.47),
        ("ÆG OG BACON SAL SØNDER FRIST", 0.54),
        ("STEGTE RIS SALLING NU", 0.94),
        ("OLIVEN MED CHIL SALLING", 0.61),
        ("RØD PEBER M OST SALLING", 1.61),
        ("HUMMUS HVIDLØG SALLING", 1.95),
        ("FRUGTSALAT K-SALAT", 0.28),
        ("MEDISTER 500G SLAGTEREN", 1.77),
        ("HVEDE SANDWICH SALLING", 0.61),
        ("SANDWICH KYL/TO SALLING NU", 1.04),
        ("KEFIR MANGO ACTIVIA", 0.62),
        ("APPELSIN M/TOP YOGGI", 1.6),
        ("DEFENCE INNOCENT", 1.48),
        ("NDUJA TULIP", 1.5),
        ("FENNIKEL SALAMI TULIP", 6.12),
        ("HUMMUS BUDGET", 1.27),
        ("MAR. SPARERIBS ANTONIUS", 1.63),
        ("GOUDA I SKIVER SALLING", 1.02),
        ("GORGONZOLA LA CAMPAGNA", 1.32),
        ("SANDWICHSKINKE BUDGET", 4.35),
        ("BLUE SPARK 0.75 L", 0.67),
        ("GULERODSRUGBR DET GODE", 1.13),
        ("SOLSIKKERUGBRØD DET GODE", 0.06),
        ("SPEGE. SDJ. 3-STJERNET", 1.75),
        ("KYLLINGEBRYST 3 STJERNET", 1.13),
        ("HØRFRØBRØD SALLING", 0.1),
        ("YOGHURT 6X50G DANONINO", 0.22),
        ("LAMMEKRONE LUDVIG", 8.12),
        ("DURUM CAFE SAND KOHBERG", 1.58),
        ("HVEDECIABATTA KOHBERG", 1.59),
        ("ØKO MEDISTER SALLING ØKO", 1.59),
        ("ISKAFFE KARAMEL PETER LARSEN", 1.96),
        ("ISKAFFE CHOCO PETER LARSEN", 0.5),
        ("HOTDOG PØLSER LANGELÆNDER", 1.22),
        ("SOLSIKKE KOHBERG", 0.88),
        ("TARTELETFYLD PREMIEUR", 0.9),
        ("YOGHURT SKOVBÆR CHEASY", 0.7),
        ("ØKO SKIVER MINI THEM", 0.94),
        ("MARINERET SVINEFILET VELSMAG", 0.83),
        ("PAD THAI VELSMAG", 0.8),
        ("PANINI M/SKINKE&OST NÆMT", 1.71),
        ("DET GODE GULEROD SCHULSTAD", 1.34),
        ("MULTIKERNE BOLLER SCHULSTAD", 0.16),
        ("SKALDYRSSALAT BORNHOLMSK", 0.72),
        ("SKINKE/OST PIZZA CASA T.", 4.65),
        ("KÆRNEMÆLK ARLA", 0.66),
        ("KOTELETTER VELSMAG", 1.58),
        ("KYLLING & OKSE 3-STJERNET", 1.43),
        ("EMPANADAS OKSE LOS TAQUEROS", 7.06),
        ("SKAGEN SANDWICH NATURLI", 0.57),
        ("PULLED CHICKEN JENSENS", 1.62),
        ("EMPANADAS KYL. LOS TAQUEROS", 2.03),
        ("REVET GOUDA LA CAMPAGNA", 1.26),
        ("JUICE HINDBÆR SOLBÆR INNOCENT", 0.25),
        ("ROASTBEEF EGELYKKE", 9.17),
        ("JUICE CITRON, LIME INNOCENT", 0.33),
        ("BONDEBRØD GAMLE MØLLE", 0.19),
        ("DANONINO 6-PAK DANONE", 1.62),
        ("MEDALJONER VELSMAG", 1.63),
        ("VEG. KARTOFFELSALAT SPIR", 0.45),
        ("GYROS AF GRIS DANISH CROWN", 0.91),
        ("PEBER/BACON PØLSER VELSMAG", 2.12),
        ("SOLSIKKERUGBRØD GAMLE MØLLE", 0.22),
        ("MORGENSTYKKER BAKERSFIELD", 1.9),
        ("PØLSER M. BACON GEIA", 2.34),
        ("PIZZATOPPING FALENGREEN", 1.89),
        ("SPICY HUMMUS LA CAMPAGNA", 0.51),
        ("OLIVEN MANDLER LA CAMPAGNA", 1.6),
        ("FYLDTE GRØNNE PEBRE LA CAMPAGNA", 0.94),
        ("RULLEPØLSE EGELYKKE", 3.86),
        ("SALTKØD EGELYKKE", 1.06),
        ("BRIE M/TRØFFEL CASTELLO", 2.95),
        ("INTENSE BLUE CASTELLO", 0.69),
        ("OPAL CHEESEMAKER", 1.31),
        ("SKINKESALAT BORNHOLMER", 1.44),
        ("TANTE K. SPEGE BORNHOLMER", 0.54),
        ("FLØDEKARTOFLER NÆMT", 0.93),
        ("LAGRET CHEDDAR CASTELLO", 4.82),
        ("FALAFEL SPIR", 1.34),
        ("PLANTEPOSTEJ HANEGAL", 3.59),
        ("KRABBESALAT K-SALAT", 0.58),
        ("MINIFRIKADELLER NÆMT", 0.56),
        ("KRYDRET KYLLING NÆMT", 2.35),
        ("FYLDT RØD PEBER LA CAMPAGNA", 0.9),
        ("OLIVEN MIX LA CAMPAGNA", 0.7),
        ("CHICKEN CASHEW NÆMT", 1.61),
        ("CHILI & INGEFÆR CASTELLO", 1.27),
        ("KYLLINGETERN NÆMT", 1.57),
        ("COLESLAW SALATMESTEREN", 0.5),
        ("RØGET FILET PÅLÆKKER", 1.49),
        ("MINI KYLLINGEPØLSER PØLSEMESTEREN", 0.84),
        ("GULDSARDEL C. VOLLSTEDT", 1.16),
        ("FRISK MOZZARELLA ØGO", 1.65),
        ("GRILLPØLSER M/OST STEFF HOULBERG", 2.6),
        ("HOTDOG PØLSER PØLSEMESTEREN", 3.24),
        ("OLIVEN/SALATOST LA CAMPAGNA", 4.69),
        ("KRANS ANANAS CASTELLO", 0.82),
        ("TOLKO PURLØG CASTELLO", 1.98),
        ("SPREAD PUCK", 0.99),
        ("MEXI-MIX REVET", 1.32),
        ("HAMBURGERRYG SMAGEN AF AARHUS", 1.29),
        ("STRACCIATELLA ZANETTI", 0.61),
        ("SKIVER ML 13% CHEASY", 0.78),
        ("PLANTGURT M/ LIME ALPRO", 1.92),
        ("YOGHURT PÆRE EGELYKKE", 0.73),
        ("OSTE PØLSER ØGO", 1.53),
        ("ØKO PISKEFLØDE 38% LØGISMOSE", 1.89),
        ("SKÆREOST 45+ XL RIBERHUS", 3.56),
        ("LANGBANE MAMMEN", 0.7),
        ("CAMEMBERT LE RUSTIQUE", 0.55),
        ("COCKTAILPØLSER NÆMT", 3.79),
        ("CREAMY WHITE CASTELLO", 1.85),
        ("GULD 45+ MAMMEN", 0.56),
        ("AGED GOUDA CASTELLO", 0.79),
        ("MODNET GLØD CASTELLO", 0.7),
        ("RØGET MØRBRAD SMAGEN AARHU", 0.94),
        ("CHEDDAR KANT CASTELLO", 1.68),
        ("FEDT M/LØG OK", 0.83),
        ("XL STEAK VELSMAG", 0.94),
        ("KOLDSKÅL ARLA", 1.78),
        ("DET GODE SOL RUGBRØD SCHULSTAD", 0.12),
        ("SANDWICH FULDKORN GAMLE MØLLE", 1.73),
        ("NATUREL KLØVER", 1.65),
        ("ØKO MINIMÆLK LØGISMOSE", 0.66),
        ("GÆR MALTESERKORS", 1.24),
        ("LF CREME FRAICHE 13% ARLA", 1.11),
        ("HAVARTI ØKO SKV THEM", 0.77),
        ("HØNSESALAT, PLUKKET K-SALAT", 0.64),
        ("SAN. KYLLING PÅLÆKKER", 1.13),
        ("BACON I SKIVER BRUNCHY", 0.76),
        ("JENSENS PULLED JENSENS", 1.0),
        ("RØGET RULLEPØLS EGELYKKE", 1.89),
        ("SKAFTEKOTELET PREMIEUR", 1.88),
        ("DRIKKE YOGHURT ACTIMEL", 0.64),
        ("VANILJE DRIK PROTEIN LAB", 0.65),
        ("SALTKARAMEL DRI PROTEIN LAB", 0.85),
        ("SLIDERS M SESAM PREMIEUR", 1.09),
        ("RUG SANDWICH KOHBERG", 1.38),
        ("BURGER BOOST SLIDERS DANISH CROWN", 3.27),
        ("HAMBURGERRYG ØGO", 0.97),
        ("SOLSTYKKER PÅGEN", 1.13),
        ("KYL.STRIMLER NÆMT", 1.66),
        ("KROGMODNET BURGERBØF PREMIEUR", 1.78),
        ("ÆGGESALAT K-SALAT", 0.71),
        ("SKAGENSALAT K-SALAT", 0.49),
        ("BRIOCHE HOTDOG NORDTHY", 1.38),
        ("JORDBÆR 4-PAK ACTIMEL", 0.97),
        ("SPICY TUNSALAT K-SALAT", 0.29),
        ("BURGERBOLLER BAKERSFIELD", 0.16),
        ("JORDBÆR ACTIMEL", 1.38),
        ("HOTDOGBRØD BAKERSFIELD", 0.17),
        ("SKOVBÆR DRIK ACTIMEL", 0.55),
        ("MAJSKAGER OST GOODFOOD", 5.25),
        ("VEGANSK LASAGNE SPIR", 1.83),
        ("WIENERPØLSER LANGELÆNDER", 4.24),
        ("KØDPØLSE, BAMSE EGELYKKE", 4.35),
        ("PLANTGURT M/ VANILJE ALPRO", 1.24),
        ("KNÆKBRØD RUG FINTON'S", 0.12),
        ("MON P'TIT BRIE FROMAGERIE", 4.71),
        ("HAVRE WASA", 1.4),
        ("PISKEFLØDE 38% ØGO", 1.0),
        ("JORDBÆR POUCH DANONINO", 1.16),
        ("ØKO SKYR NATUR. LØGISMOSE", 1.83),
        ("PØLSEBRØD BAKERSFIELD", 4.42),
        ("SKYR JORDBÆR EGELYKKE", 1.47),
        ("BAGELS M SESAM PREMIEUR", 1.13),
        ("INGEFÆR/HIND ØGO", 0.81),
        ("CHEESECAKE OREO", 1.31),
        ("KYLLING-BACON GRAASTEN", 1.9),
        ("BURGER BOOST DANISH CROWN", 1.88),
        ("PISKEFLØDE SALLING ØKO", 0.87),
        ("STÆRK DRESSING SUPER KRÆS", 1.37),
        ("KART.SALAT PERS GRAASTEN", 0.21),
        ("ØKO KÆRNEMÆLK NATURMÆLK", 0.35),
        ("ØKO LETMÆLK NATURMÆLK", 0.58),
        ("MINI MOZZARELLA FELLINO", 1.61),
        ("OSTESAUCE PRINCIP", 1.36),
        ("KLASSISK DRES SUPER KRÆS", 2.0),
        ("ØKO SKUMMETMÆLK ARLA", 0.62),
        ("KNÆKBRØD RODFR. ALL IN ONE", 0.21),
        ("PASTASALAT KYLL./KAR NÆMT", 1.65),
        ("CHIAGRØD M/ MANGO THE PROTEIN KITCHEN", 1.48),
        ("SOLSIKKE RUGBRØD ØGO", 0.11),
        ("KLASSISK 3-STJERNET", 1.22),
        ("SNACK STICKS EGELYKKE", 1.72),
        ("BEARNAISESAUCE LØGISMOSE", 1.99),
        ("GRILLPØLSER PØLSERIET", 1.97),
        ("SKIVER PORT SALUT", 0.52),
        ("SANDW. ÆG/BACON NÆMT", 1.92),
        ("TPK ITALIAN PASTA TPK", 1.98),
        ("SØDMÆLKSBRØD SCHULSTAD", 0.37)
    ]

    estimated_emissions = dict(estimated_emissions)

    try:
        return estimated_emissions[product_name]
    except:
        return 0